version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "src/Volvox.Apollo.Web/ClientApp"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "ethan-guest"
    reviewers:
      - "ethan-guest"
    labels:
      - "frontend"
      - "dependencies"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "BillChirico"
      - "ethan-guest"
    reviewers:
      - "BillChirico"
      - "ethan-guest"
    labels:
      - "backend"
      - "dependencies"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "BillChirico"
      - "mhallmark"
    reviewers:
      - "BillChirico"
      - "mhallmark"
    labels:
      - "docker"
      - "dependencies"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "BillChirico"
      - "mhallmark"
    reviewers:
      - "BillChirico"
      - "mhallmark"
    labels:
      - "github-actions"
      - "dependencies"

  # Maintain dependencies for all dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "BillChirico"
      - "ethan-guest"
    reviewers:
      - "BillChirico"
      - "ethan-guest"
    labels:
      - "dependencies"
